apiVersion: v1
kind: Service
metadata:
  name: "{{ include "helm.fullname" . }}-frontend-server"
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontendServerService.type }}
  ports:
    - port: {{ .Values.frontendServerService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "helm.fullname" . }}-frontend-server
