apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "helm.fullname" . }}-frontend-server"
type: Opaque
stringData: 
  {{- range .Values.frontendServerSecrets}}
    {{.name}} : {{.value}}
  {{- end }}