apiVersion: v1
kind: Service
metadata:
  name: "{{ include "helm.fullname" . }}-read"
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.readService.type }}
  ports:
    - port: {{ .Values.readService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "helm.fullname" . }}-read
