apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-stt
  labels:
    app: {{ include "helm.fullname" . }}-stt
spec:
  {{- if not .Values.sttAutoscaling.enabled }}
  replicas: {{ .Values.sttReplicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "helm.fullname" . }}-stt
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "helm.fullname" . }}-stt
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.sttImage.repository }}:{{ .Values.sttImage.tag | default .Chart.AppVersion }}"
          envFrom:
          - secretRef:
              name: "{{ .Chart.Name }}-stt"
          imagePullPolicy: {{ .Values.sttImage.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /status
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: http
          resources:
            {{- toYaml .Values.sttResources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
