apiVersion: v1
kind: PersistentVolume
metadata:
  name: bpa-volume-read
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/temp"